server:
  port: 8765

spring:
  application:
    name: zuul-gateway

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaul-zone: http://localhost:8761/eureka/

zuul:
  routes:
    users:
      path: /users/**
      serviceId: users-service